export const {
  NEXT_PUBLIC_APP_DOMAIN: APP_DOMAIN,
  NEXT_PUBLIC_STORAGE_BUCKET: STORAGE_BUCKET,
  NEXT_PUBLIC_SUPABASE_URL: SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: SUPABASE_ANON_KEY
} = process.env
