name: Ping to Supabase

on:
  schedule:
    - cron: '0 9 * * 1,4' # Runs at 9:00 AM UTC every Monday and Thursday
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase Client
        run: npm install @supabase/supabase-js --force

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node -e "
          (async () => {
            try {
              // Debugging: Log environment variables (optional)
              console.log('Supabase URL:', $SUPABASE_URL);
              console.log('Supabase Key:', $SUPABASE_KEY);

              
            } catch (err) {
              // Log and exit with error
              console.error('Error pinging Supabase:', err.message);
              process.exit(1);
            }
          })();
          "
