name: Ping to Supabase

on:
  schedule:
    - cron: '0 9 * * 1,4' # Runs at 9:00 AM UTC every Monday and Thursday
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Ping Supabase
      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Pinging Supabase at $SUPABASE_URL"
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -X GET "$SUPABASE_URL/rest/v1/" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY")

          if [ "$response" -eq 200 ]; then
            echo "✅ Ping successful!"
          else
            echo "❌ Ping failed with status $response"
            exit 1
          fi
